import { useState } from 'react';
import { FileText, RefreshCw, XCircle } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { apiClient } from '../api';
import { useToast } from '../app/providers';
import { useBills, useRefunds } from '../hooks';
import { errorMessage, formatDate } from '../lib';
import { Button, EmptyState, ErrorState, Money, SectionHeading } from '../components/store-ui';
import { AccountIntro } from './AuthPages';

export function BillsPage() { const query = useBills(); const [total, setTotal] = useState<number | null>(null); const loadTotal = async () => { try { const result = await apiClient.bills.totalSpent(); setTotal(result.totalSpent); } catch { setTotal(null); } }; if (query.isLoading) return <div className="skeleton h-80 rounded-3xl" />; if (query.isError) return <ErrorState onRetry={() => void query.refetch()} />; const bills = query.data ?? []; return <div className="animate-float-in"><AccountIntro title="Bills" body="Your payment history, kept simple." /><div className="mb-5 flex flex-wrap gap-3"><div className="rounded-2xl border border-line bg-white px-4 py-3"><span className="block text-xs text-muted">Paid bills</span><strong className="text-lg text-ink">{bills.filter(bill => (bill.Status ?? '').toLowerCase() === 'paid').length}</strong></div><button onClick={() => void loadTotal()} className="rounded-2xl border border-line bg-white px-4 py-3 text-left hover:border-leaf"><span className="block text-xs text-muted">Total spent</span><strong className="text-lg text-leaf-dark">{total === null ? 'Show total' : <Money value={total} />}</strong></button></div>{bills.length ? <div className="grid gap-3">{bills.map(bill => <div key={bill.BillId} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-line bg-white p-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-leaf-soft text-leaf"><FileText size={18} /></span><div><p className="text-sm font-bold">Bill #{bill.BillId} · Order #{bill.OrderId}</p><p className="mt-1 text-xs text-muted">{formatDate(bill.CreatedAt)} · {bill.Status}</p></div></div><Money value={bill.FinalAmount} className="font-extrabold text-ink" /></div>)}</div> : <EmptyState icon={<FileText />} title="No bills yet" body="Paid order receipts will appear here." />}</div>; }

export function RefundsPage() { const query = useRefunds(); const { showToast } = useToast(); const queryClient = useQueryClient(); const cancel = async (id: number) => { try { await apiClient.refunds.cancel(id); showToast('Refund request canceled.'); await queryClient.invalidateQueries({ queryKey: ['refunds'] }); } catch (error) { showToast(errorMessage(error, 'Could not cancel this refund request.'), 'error'); } }; if (query.isLoading) return <div className="skeleton h-80 rounded-3xl" />; if (query.isError) return <ErrorState onRetry={() => void query.refetch()} />; const refunds = query.data ?? []; return <div className="animate-float-in"><AccountIntro title="Refunds" body="Review requests raised for delivered orders." />{refunds.length ? <div className="grid gap-3">{refunds.map(refund => <div key={refund.RefundId} className="rounded-2xl border border-line bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold text-ink">Refund #{refund.RefundId} · Order #{refund.OrderId}</p><p className="mt-1 text-xs text-muted">{refund.Reason || 'No reason provided'} · {formatDate(refund.CreatedAt)}</p></div><span className="rounded-full bg-[#fff5dc] px-3 py-1 text-xs font-bold capitalize text-warning">{refund.Status ?? 'pending'}</span></div><div className="mt-4 flex items-center justify-between"><Money value={refund.RefundAmount} className="text-base font-extrabold text-ink" />{(refund.Status ?? '').toLowerCase() === 'pending' && <Button variant="danger" onClick={() => void cancel(refund.RefundId)}><XCircle size={15} /> Cancel request</Button>}</div></div>)}</div> : <EmptyState icon={<RefreshCw />} title="No refund requests" body="Eligible delivered orders can start a refund request from their detail page." />}</div>; }
