import { FormEvent, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Eye, EyeOff, ShoppingBag } from 'lucide-react';
import { apiClient } from '../api';
import { useAuth, useToast } from '../app/providers';
import { errorMessage } from '../lib';
import { Button } from '../components/store-ui';
import { AuthLayout } from '../layouts/StoreLayout';

function Field({ label, type = 'text', value, onChange, placeholder, required = true, disabled = false }: { label: string; type?: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean; disabled?: boolean }) { const [show, setShow] = useState(false); const password = type === 'password'; return <label className="block"><span className="mb-1.5 block text-sm font-semibold text-ink">{label}</span><span className="relative block"><input required={required} disabled={disabled} type={password && show ? 'text' : type} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="h-12 w-full rounded-xl border border-line bg-white px-3.5 text-sm text-ink outline-none transition placeholder:text-[#a1afa4] focus:border-leaf focus:ring-4 focus:ring-[#e3f2e7] disabled:bg-canvas disabled:text-muted" />{password && <button type="button" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(value => !value)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted">{show ? <EyeOff size={17} /> : <Eye size={17} />}</button>}</span></label>; }

function BrandMark() { return <Link to="/" className="mb-8 flex items-center justify-center gap-2.5"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-leaf text-white"><ShoppingBag size={22} /></span><span className="display text-xl font-extrabold">Green<span className="text-leaf">Basket</span></span></Link>; }

export function LoginPage() {
  const { login } = useAuth(); const { showToast } = useToast(); const navigate = useNavigate(); const location = useLocation(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false);
  const params = new URLSearchParams(location.search); const requestedReturnUrl = params.get('returnUrl') || '/'; const returnUrl = requestedReturnUrl.startsWith('/') && !requestedReturnUrl.startsWith('//') ? requestedReturnUrl : '/';
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await login({ Email: email.trim(), Password: password }); showToast('Welcome back!'); navigate(returnUrl); } catch (error) { showToast(errorMessage(error, 'Could not sign in. Check your email and password.'), 'error'); } finally { setBusy(false); } };
  return <AuthLayout><BrandMark /><div className="rounded-3xl border border-line bg-white p-6 shadow-[0_20px_60px_rgba(32,62,42,.08)] sm:p-8"><h1 className="display text-2xl font-extrabold text-ink">Welcome back</h1><p className="mt-2 text-sm text-muted">Sign in to keep your basket and orders in sync.</p><form onSubmit={submit} className="mt-7 space-y-4"><Field label="Email" type="email" value={email} onChange={setEmail} placeholder="you@example.com" /><Field label="Password" type="password" value={password} onChange={setPassword} placeholder="At least 6 characters" /><Button disabled={busy} className="mt-2 h-12 w-full">{busy ? 'Signing in…' : 'Sign in'}</Button></form><p className="mt-6 text-center text-sm text-muted">Don't have an account? <Link to={`/register${returnUrl !== '/' ? `?returnUrl=${encodeURIComponent(returnUrl)}` : ''}`} className="font-bold text-leaf hover:text-leaf-dark">Create one</Link></p></div><Link to="/" className="mt-6 flex items-center justify-center gap-1 text-sm font-semibold text-muted hover:text-leaf"><ArrowLeft size={15} /> Continue shopping</Link></AuthLayout>;
}

export function RegisterPage() {
  const { register } = useAuth(); const { showToast } = useToast(); const navigate = useNavigate(); const [form, setForm] = useState({ Name: '', Email: '', Phone: '', Address: '', Password: '', Confirm: '' }); const [busy, setBusy] = useState(false); const set = (key: keyof typeof form) => (value: string) => setForm(current => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (form.Password.length < 6) { showToast('Password must be at least 6 characters.', 'error'); return; } if (form.Password !== form.Confirm) { showToast('Passwords do not match.', 'error'); return; } setBusy(true); try { await register({ Name: form.Name.trim(), Email: form.Email.trim(), Password: form.Password, Phone: form.Phone.trim() || null, Address: form.Address.trim() || null }); showToast('Account created. Please sign in.'); navigate('/login'); } catch (error) { showToast(errorMessage(error, 'Could not create your account.'), 'error'); } finally { setBusy(false); } };
  return <AuthLayout><BrandMark /><div className="rounded-3xl border border-line bg-white p-6 shadow-[0_20px_60px_rgba(32,62,42,.08)] sm:p-8"><h1 className="display text-2xl font-extrabold text-ink">Create your account</h1><p className="mt-2 text-sm text-muted">Save your details for a faster checkout next time.</p><form onSubmit={submit} className="mt-7 space-y-4"><Field label="Full name" value={form.Name} onChange={set('Name')} placeholder="Nguyen Van A" /><Field label="Email" type="email" value={form.Email} onChange={set('Email')} placeholder="you@example.com" /><div className="grid gap-4 sm:grid-cols-2"><Field label="Phone" value={form.Phone} onChange={set('Phone')} placeholder="090..." required={false} /><Field label="Address" value={form.Address} onChange={set('Address')} placeholder="Delivery address" required={false} /></div><Field label="Password" type="password" value={form.Password} onChange={set('Password')} placeholder="At least 6 characters" /><Field label="Confirm password" type="password" value={form.Confirm} onChange={set('Confirm')} placeholder="Repeat password" /><Button disabled={busy} className="mt-2 h-12 w-full">{busy ? 'Creating account…' : 'Create account'}</Button></form><p className="mt-6 text-center text-sm text-muted">Already have an account? <Link to="/login" className="font-bold text-leaf hover:text-leaf-dark">Sign in</Link></p></div><Link to="/" className="mt-6 flex items-center justify-center gap-1 text-sm font-semibold text-muted hover:text-leaf"><ArrowLeft size={15} /> Continue shopping</Link></AuthLayout>;
}

export function AccountProfilePage() {
  const { customer, refresh } = useAuth(); const { showToast } = useToast(); const [form, setForm] = useState({ Name: customer?.Name ?? '', Phone: customer?.Phone ?? '', Address: customer?.Address ?? '' }); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await apiClient.auth.updateProfile({ Name: form.Name.trim(), Phone: form.Phone.trim(), Address: form.Address.trim() }); await refresh(); showToast('Profile updated.'); } catch (error) { showToast(errorMessage(error, 'Could not update profile.'), 'error'); } finally { setBusy(false); } };
  return <div className="mx-auto max-w-2xl animate-float-in"><AccountIntro title="Profile" body="Keep your delivery details up to date." /><form onSubmit={submit} className="space-y-5 rounded-3xl border border-line bg-white p-6 sm:p-8"><Field label="Full name" value={form.Name} onChange={value => setForm(current => ({ ...current, Name: value }))} /><Field label="Email" value={customer?.Email ?? ''} onChange={() => undefined} required={false} disabled /><Field label="Phone" value={form.Phone} onChange={value => setForm(current => ({ ...current, Phone: value }))} required={false} /><label className="block"><span className="mb-1.5 block text-sm font-semibold text-ink">Delivery address</span><textarea value={form.Address} onChange={event => setForm(current => ({ ...current, Address: event.target.value }))} rows={3} className="w-full rounded-xl border border-line px-3.5 py-3 text-sm outline-none focus:border-leaf focus:ring-4 focus:ring-[#e3f2e7]" /></label><Button disabled={busy}>{busy ? 'Saving…' : 'Save changes'}</Button></form></div>;
}

export function SecurityPage() { const { showToast } = useToast(); const [form, setForm] = useState({ old: '', next: '', confirm: '' }); const [busy, setBusy] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); if (form.next.length < 6 || form.next !== form.confirm) { showToast(form.next.length < 6 ? 'New password must be at least 6 characters.' : 'Passwords do not match.', 'error'); return; } setBusy(true); try { await apiClient.auth.changePassword({ OldPassword: form.old, NewPassword: form.next }); showToast('Password changed.'); setForm({ old: '', next: '', confirm: '' }); } catch (error) { showToast(errorMessage(error, 'Could not change password.'), 'error'); } finally { setBusy(false); } }; return <div className="mx-auto max-w-2xl animate-float-in"><AccountIntro title="Security" body="Use a strong password to keep your account safe." /><form onSubmit={submit} className="space-y-5 rounded-3xl border border-line bg-white p-6 sm:p-8"><Field label="Current password" type="password" value={form.old} onChange={value => setForm(current => ({ ...current, old: value }))} /><Field label="New password" type="password" value={form.next} onChange={value => setForm(current => ({ ...current, next: value }))} /><Field label="Confirm new password" type="password" value={form.confirm} onChange={value => setForm(current => ({ ...current, confirm: value }))} /><Button disabled={busy}>{busy ? 'Updating…' : 'Change password'}</Button></form></div>; }

export function AccountIntro({ title, body }: { title: string; body: string }) { return <div className="mb-6"><p className="mb-1 text-xs font-bold uppercase tracking-[.16em] text-leaf">My account</p><h1 className="display text-3xl font-extrabold text-ink">{title}</h1><p className="mt-2 text-sm text-muted">{body}</p></div>; }
