import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { ArrowRight, ChevronLeft, Clock3, Leaf, ShieldCheck, Truck, Utensils } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { apiClient } from '../api';
import { useAuth, useCart, useToast } from '../app/providers';
import { productInStock, productName, supplierName } from '../app/types';
import { useCatalog, useCategories, useDebouncedValue, useProduct } from '../hooks';
import { Button, CategoryPills, EmptyState, ErrorState, LinkArrow, Money, ProductGrid, ProductImage, ProductSkeleton, QuantityControl, SearchBar, SectionHeading } from '../components/store-ui';

export function HomePage() {
  const { data: products = [], isLoading, isError, refetch } = useCatalog();
  const { data: categories = [] } = useCategories();
  const { add, quantities, update } = useCart(); const { isAuthenticated } = useAuth(); const { showToast } = useToast(); const navigate = useNavigate();
  const available = useMemo(() => products.filter(productInStock), [products]);
  const categorySections = categories.map(category => ({ category, products: products.filter(product => product.CategoryId === category.CategoryId && productInStock(product)).slice(0, 4) })).filter(section => section.products.length);
  const quickAdd = (product: (typeof products)[number]) => { if (!isAuthenticated) { showToast('Sign in to add items to your cart.', 'info'); navigate('/login?returnUrl=%2F'); return; } void add({ ProductId: product.ProductId, Quantity: 1 }); };
  return <div className="animate-float-in space-y-12">
    <section className="relative overflow-hidden rounded-[2rem] bg-[#dff1e3] px-6 py-10 sm:px-10 sm:py-14 lg:px-16"><div className="relative z-10 max-w-xl"><span className="inline-flex items-center gap-2 rounded-full bg-white/80 px-3 py-1.5 text-xs font-bold text-leaf-dark"><Leaf size={14} /> Fresh picks for every day</span><h1 className="display mt-5 text-4xl font-extrabold leading-[1.08] tracking-tight text-[#163a23] sm:text-5xl lg:text-6xl">Good food,<br /><span className="text-leaf">good mood.</span></h1><p className="mt-4 max-w-md text-base leading-7 text-[#477254]">Everyday groceries, carefully picked and delivered to your door without the supermarket run.</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={() => navigate('/products')}>Shop all products <ArrowRight size={17} /></Button><Button variant="outline" onClick={() => navigate('/search?q=healthy')}>Find something healthy</Button></div></div><div className="pointer-events-none absolute -right-12 -top-20 h-72 w-72 rounded-full bg-[#c4e7ca] opacity-80" /><div className="pointer-events-none absolute -bottom-24 right-10 h-64 w-64 rounded-full bg-[#f7d995] opacity-80" /><div className="absolute bottom-0 right-6 hidden w-72 text-[10rem] leading-none lg:block">🥬</div></section>
    <section className="grid gap-3 sm:grid-cols-3"><ValuePill icon={<Truck size={20} />} title="Fast delivery" body="To your door, simply." /><ValuePill icon={<ShieldCheck size={20} />} title="Quality checked" body="Freshness comes first." /><ValuePill icon={<Clock3 size={20} />} title="Easy checkout" body="Less steps, more time." /></section>
    <section><SectionHeading eyebrow="Explore" title="Shop by category" action={<LinkArrow to="/products">View all</LinkArrow>} /><div className="hide-scrollbar flex gap-3 overflow-x-auto pb-2">{categories.slice(0, 8).map((category, index) => <Link key={category.CategoryId} to={`/category/${category.CategoryId}`} className="group min-w-[116px] rounded-2xl border border-line bg-white p-4 text-center transition hover:-translate-y-1 hover:border-leaf hover:shadow-sm sm:min-w-0 sm:flex-1"><span className={`mx-auto flex h-14 w-14 items-center justify-center rounded-2xl text-2xl ${['bg-[#fff3d7]', 'bg-[#e2f4e6]', 'bg-[#e9e5fb]', 'bg-[#fde5e2]'][index % 4]}`}>{['🥤', '🍜', '🧼', '🍪', '🥦', '🧴'][index % 6]}</span><span className="mt-3 block truncate text-sm font-bold text-ink group-hover:text-leaf">{category.CategoryName}</span></Link>)}</div></section>
    <section><SectionHeading eyebrow="Available now" title="Good stuff, ready to go" action={<LinkArrow to="/products">See everything</LinkArrow>} />{isLoading ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <ProductSkeleton key={index} />)}</div> : isError ? <ErrorState onRetry={() => void refetch()} /> : available.length ? <ProductGrid products={available.slice(0, 8)} cartQuantities={quantities} onAdd={quickAdd} onUpdate={(product, quantity) => void update(product.ProductId, { Quantity: quantity })} /> : <EmptyState icon={<Utensils />} title="No products available yet" body="Check back soon for fresh grocery picks." action={<Button onClick={() => navigate('/products')}>Browse catalog</Button>} />}</section>
    {categorySections.slice(0, 2).map(({ category, products: sectionProducts }) => <section key={category.CategoryId}><SectionHeading eyebrow="For your kitchen" title={category.CategoryName} action={<LinkArrow to={`/category/${category.CategoryId}`}>View category</LinkArrow>} /><ProductGrid products={sectionProducts} cartQuantities={quantities} onAdd={quickAdd} onUpdate={(product, quantity) => void update(product.ProductId, { Quantity: quantity })} /></section>)}
  </div>;
}

function ValuePill({ icon, title, body }: { icon: ReactNode; title: string; body: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-line bg-white px-4 py-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-leaf-soft text-leaf">{icon}</span><div><p className="text-sm font-bold text-ink">{title}</p><p className="text-xs text-muted">{body}</p></div></div>; }

export function ProductsPage() {
  const location = useLocation(); const navigate = useNavigate(); const params = useParams();
  const query = new URLSearchParams(location.search); const initialSearch = query.get('q') ?? ''; const [search, setSearch] = useState(initialSearch); const [categoryId, setCategoryId] = useState<number | undefined>(params.id ? Number(params.id) : undefined); const debouncedSearch = useDebouncedValue(search);
  useEffect(() => { setSearch(initialSearch); setCategoryId(params.id ? Number(params.id) : undefined); }, [initialSearch, params.id]);
  const { data: categories = [] } = useCategories(); const { data: products = [], isLoading, isError, refetch } = useCatalog({ keyword: debouncedSearch, categoryId });
  const { isAuthenticated } = useAuth(); const { add, quantities, update } = useCart(); const { showToast } = useToast();
  const submit = () => { const value = search.trim(); navigate(value ? `/search?q=${encodeURIComponent(value)}` : categoryId ? `/category/${categoryId}` : '/products'); };
  const setCategory = (id?: number) => { setCategoryId(id); setSearch(''); navigate(id ? `/category/${id}` : '/products'); };
  const quickAdd = (product: (typeof products)[number]) => { if (!isAuthenticated) { showToast('Sign in to add items to your cart.', 'info'); navigate(`/login?returnUrl=${encodeURIComponent(location.pathname)}`); return; } void add({ ProductId: product.ProductId, Quantity: 1 }); };
  const title = initialSearch ? `Results for “${initialSearch}”` : categoryId ? categories.find(category => category.CategoryId === categoryId)?.CategoryName ?? 'Category' : 'All products';
  return <div className="animate-float-in space-y-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.16em] text-leaf">Discover</p><h1 className="display text-3xl font-extrabold text-ink sm:text-4xl">{title}</h1><p className="mt-2 text-sm text-muted">Find everyday essentials, snacks and little treats.</p></div><div className="w-full lg:max-w-md"><SearchBar value={search} onChange={setSearch} onSubmit={submit} /></div></div><CategoryPills categories={categories} selected={categoryId} onSelect={setCategory} />{isLoading ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{Array.from({ length: 8 }, (_, index) => <ProductSkeleton key={index} />)}</div> : isError ? <ErrorState onRetry={() => void refetch()} /> : products.length ? <ProductGrid products={products} cartQuantities={quantities} onAdd={quickAdd} onUpdate={(product, quantity) => void update(product.ProductId, { Quantity: quantity })} /> : <EmptyState icon={<Leaf />} title="No products found" body="Try another search or browse every category." action={<Button onClick={() => { setSearch(''); setCategory(); }}>Clear filters</Button>} />}</div>;
}

export function ProductDetailPage() {
  const { id } = useParams(); const productId = Number(id); const navigate = useNavigate(); const { data: product, isLoading, isError, refetch } = useProduct(productId); const { isAuthenticated } = useAuth(); const { add, quantities, update } = useCart(); const { showToast } = useToast(); const [quantity, setQuantity] = useState(1);
  if (isLoading) return <div className="grid gap-8 md:grid-cols-2"> <div className="skeleton aspect-square rounded-[2rem]" /><div className="space-y-4 pt-5"><div className="skeleton h-5 w-24 rounded" /><div className="skeleton h-12 w-4/5 rounded" /><div className="skeleton h-8 w-32 rounded" /></div></div>;
  if (isError || !product || product.Deleted) return <ErrorState message="Product not found or no longer available." onRetry={() => void refetch()} />;
  const addNow = async () => { if (!isAuthenticated) { showToast('Sign in to add items to your cart.', 'info'); navigate(`/login?returnUrl=${encodeURIComponent(`/products/${productId}`)}`); return false; } await add({ ProductId: product.ProductId, Quantity: quantity }); return true; };
  return <div className="animate-float-in"><button onClick={() => navigate(-1)} className="mb-6 inline-flex items-center gap-1 text-sm font-bold text-muted hover:text-leaf"><ChevronLeft size={17} /> Back to shopping</button><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(0,.85fr)] lg:gap-14"><div className="flex aspect-square items-center justify-center overflow-hidden rounded-[2rem] bg-[#eff6f0] p-8 sm:p-14"><ProductImage product={product} className="h-full w-full" /></div><div className="flex flex-col justify-center"><span className="text-sm font-bold text-leaf">{product.Category?.CategoryName ?? 'Grocery essential'}</span><h1 className="display mt-3 text-3xl font-extrabold leading-tight text-ink sm:text-5xl">{productName(product)}</h1><div className="mt-5"><Money value={product.Price} className="text-2xl font-extrabold text-leaf-dark" /><span className="ml-2 text-sm text-muted">/ {product.Unit ?? 'unit'}</span></div><p className={`mt-4 text-sm font-bold ${productInStock(product) ? 'text-leaf' : 'text-danger'}`}>{productInStock(product) ? `✓ In stock: ${product.Quantity}` : 'Currently out of stock'}</p>{product.Description && <p className="mt-6 max-w-lg text-sm leading-7 text-muted">{product.Description}</p>}<div className="mt-8 flex flex-wrap items-center gap-3"><QuantityControl value={quantity} min={1} max={product.Quantity ?? undefined} onChange={setQuantity} disabled={!productInStock(product)} /><Button disabled={!productInStock(product)} onClick={() => void addNow()} className="min-w-44">Add to cart</Button><Button variant="outline" disabled={!productInStock(product)} onClick={() => { void addNow().then(ok => { if (ok) navigate('/cart'); }).catch(() => undefined); }}>Buy now</Button></div><div className="mt-9 grid gap-3 border-t border-line pt-6 text-sm"><Meta label="Unit" value={product.Unit ?? '—'} /><Meta label="Barcode" value={product.Barcode ?? '—'} /><Meta label="Supplier" value={supplierName(product)} /></div></div></div></div>;
}

function Meta({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><span className="text-muted">{label}</span><span className="font-semibold text-ink">{value}</span></div>; }
